---
- name: Install and Deploy docker on linuxclient1
  hosts: 192.168.0.215
  become: True
  become_user: root
  
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: you-utils
        state: present

    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          -containerd.io
          - docker-buildx-plugin
          -docker-compose-plugin

    - name: Start Docker service using the systemd module
        
    - name: log into docker hub registry using the docker_login module

    - name: Pull image and create the container using docker_container
    
    - name: Start the container using docker_container
