---
- name: Install and Deploy docker on linuxclient1
  hosts: 192.168.0.215
  become: true
  become_user: root

  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present

    - name: Download Docker repository file using the get_url
      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages (engine) using yum module
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install python3 and python3-pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure python3-pip is installed
      yum:
        name: python3-pip
        state: present
        
    - name: Install docker-SDK
      pip:
       name: docker
       executable: /usr/bin/pip3



- name: Deploy Container
  hosts: 192.168.0.215
  become: true

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: /usr/bin/pip3
        state: present

    - name: Check if Docker image exists
      docker_image_facts:
        name: brianbudowick/devopsfinal:latest
      register: docker_image_result

    - name: Pull image if it doesn't exist
      docker_image:
        name: brianbudowick/devopsfinal:latest
      when: not docker_image_result.exists

    - name: Start the container using docker_container
      docker_container:
        name: tomcat_devops
        image: brianbudowick/devopsfinal:latest
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8080:8080"

    - name: Log out of DockerHub
      docker_login: 
        state: absent
